language: java
jdk:
  - oraclejdk8
before_install:
  openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in currency-service-fixerio/src/main/resources/external.properties.enc -out currency-service-fixerio/src/main/resources/external.properties -d
